### ISSUE TITLE
Problems with with latest commit

### ISSUE THREAD

**Issue by tonycpsu** [mk-fg/layered-yaml-attrdict-config#11]
The latest commit to support dicts inside sequences is giving me a couple of different stack traces from AttrDict.from_yaml() with valid YAML input. 

First conf file:

```yaml
foo: 1
```

Stack trace from above:

```python
>>> import lya
>>> lya.AttrDict.from_yaml("config.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 92, in from_yaml
    with open(path_or_file) as src: return src_load(src)
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 89, in <lambda>
    src_load = lambda src: cls.from_data(yaml.load(src, OrderedDictYAMLLoader))
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 85, in from_data
    return cls(data)
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 62, in __init__
    super(AttrDict, self).__init__(*argz, **kwz)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 57, in __init__
    self.__update(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 563, in update
    self[key] = other[key]
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 66, in __setitem__
    super(AttrDict, self).__setitem__(k, self.map_types(v))
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 79, in map_types
    return type(data)(map(cls.map_types, data))
TypeError: argument 2 to map() must support iteration
```
Second conf file:

```yaml
foo: Foo
bar:
- baz:
    A:
    - A
    - B
    - C
    - D
    - E
    B:
    - F
    - G
```

Stack trace:

```python
>>> import lya
>>> lya.AttrDict.from_yaml("config.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 92, in from_yaml
    with open(path_or_file) as src: return src_load(src)
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 89, in <lambda>
    src_load = lambda src: cls.from_data(yaml.load(src, OrderedDictYAMLLoader))
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 85, in from_data
    return cls(data)
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 62, in __init__
    super(AttrDict, self).__init__(*argz, **kwz)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 57, in __init__
    self.__update(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 563, in update
    self[key] = other[key]
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 66, in __setitem__
    super(AttrDict, self).__setitem__(k, self.map_types(v))
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 79, in map_types
    return type(data)(map(cls.map_types, data))
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 79, in map_types
    return type(data)(map(cls.map_types, data))
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 79, in map_types
    return type(data)(map(cls.map_types, data))
  File "/usr/local/lib/python2.7/site-packages/lya/lya.py", line 79, in map_types
    return type(data)(map(cls.map_types, data))
```

etc. until maximum recursion is exceeded.

For now I'm using the previous commit to avoid these errors.

**Comment by mk-fg** [comment]
Thanks!

Error was:
```
-               if not isinstance(data, (list, tuple)):
+               if isinstance(data, (list, tuple)):
```

Not sure whether I tested it at all, probably not ;(
